# Generated by Django 6.0.5 on 2026-06-08 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('national_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_daily_limit', models.PositiveIntegerField(default=10)),
                ('default_monthly_limit', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=10)),
                ('monthly_limit', models.PositiveIntegerField(default=100)),
                ('daily_usage', models.PositiveIntegerField(default=0)),
                ('monthly_usage', models.PositiveIntegerField(default=0)),
                ('last_usage_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('citizen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='registary.citizen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
