# Generated by Django 6.0.5 on 2026-06-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registary', '0003_userprofile_address_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
